services:
  fyr:
    build: .
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html/writetothem
      - ./conf/general.docker:/var/www/html/writetothem/conf/general
      - ./conf/httpd.conf.docker:/etc/apache2/sites-available/000-default.conf
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || wget -qO- http://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=fyr
      - POSTGRES_PASSWORD=fyr
      - POSTGRES_DB=fyr
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      # Wait for Postgres to accept connections using the configured DB/user
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\" -h localhost"]
      interval: 1s
      timeout: 5s
      retries: 20

volumes:
  postgres_data: