#!/usr/bin/perl -w -I../../perllib -I../../../perllib
#
# server:
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: queue,v 1.1 2004-11-08 18:09:31 francis Exp $';

use FCGI;
use FYR;
use FYR::Queue;
use mySociety::DaDem;
use RABX;
use XMLRPC::Transport::HTTP;

#mySociety::DaDem::configure('http://services.mysociety.org/dadem');
mySociety::DaDem::configure('http://localhost/services/dadem');

use mySociety::WatchUpdate;
my $W = new mySociety::WatchUpdate();

my $req = FCGI::Request();

while ($req->Accept() >= 0) {
    if ($ENV{REQUEST_METHOD} eq 'POST' and $ENV{CONTENT_TYPE} eq 'text/xml') {
        my $s = XMLRPC::Transport::HTTP::CGI->dispatch_to('FYR::Queue')->handle();
    } else {
        RABX::Server::CGI::dispatch(
                'FYR.Queue.create' => sub {
                    return FYR::Queue->create(@_);
                },
                'FYR.Queue.write' => sub {
                    return FYR::Queue->write(@_);
                },
                'FYR.Queue.secret' => sub {
                    return FYR::Queue->secret(@_);
                },
                'FYR.Queue.confirm_email' => sub {
                    return FYR::Queue->confirm_email(@_);
                }
            );
    }
    $W->exit_if_changed();
}




