<?php
/* Automatically generated by fyr/bin/stats-yearly-zeitgeist */

$zeitgeist_by_summary_type_2005 = array(
    'scotland' => array(
        'dispatched_success' => '929',
        'responded' => '158',
        'responded_outof' => '573',
        'responded_mean' => '0.275741710296684',
        'responded_95_low' => '0.257072727354846',
        'responded_95_high' => '0.294410693238522',
        'firsttime' => '202',
        'firsttime_outof' => '538',
        'firsttime_mean' => '0.37546468401487',
        'firsttime_95_low' => '0.354587500444881',
        'firsttime_95_high' => '0.396341867584859',
    ),

    'europe' => array(
        'dispatched_success' => '7069',
        'responded' => '2087',
        'responded_outof' => '3970',
        'responded_mean' => '0.525692695214106',
        'responded_95_low' => '0.517767670515297',
        'responded_95_high' => '0.533617719912915',
        'firsttime' => '1322',
        'firsttime_outof' => '3630',
        'firsttime_mean' => '0.364187327823691',
        'firsttime_95_low' => '0.356200511585049',
        'firsttime_95_high' => '0.372174144062334',
    ),

    'london' => array(
        'dispatched_success' => '569',
        'responded' => '192',
        'responded_outof' => '342',
        'responded_mean' => '0.56140350877193',
        'responded_95_low' => '0.534571259196425',
        'responded_95_high' => '0.588235758347434',
        'firsttime' => '110',
        'firsttime_outof' => '308',
        'firsttime_mean' => '0.357142857142857',
        'firsttime_95_low' => '0.329840329030127',
        'firsttime_95_high' => '0.384445385255587',
    ),

    'westminster' => array(
        'dispatched_success' => '29976',
        'responded' => '14051',
        'responded_outof' => '22231',
        'responded_mean' => '0.632045342089875',
        'responded_95_low' => '0.628810956669106',
        'responded_95_high' => '0.635279727510643',
        'firsttime' => '9416',
        'firsttime_outof' => '21514',
        'firsttime_mean' => '0.437668494933532',
        'firsttime_95_low' => '0.434286224972122',
        'firsttime_95_high' => '0.441050764894941',
    ),

    'wales' => array(
        'dispatched_success' => '252',
        'responded' => '105',
        'responded_outof' => '180',
        'responded_mean' => '0.583333333333333',
        'responded_95_low' => '0.546586787346325',
        'responded_95_high' => '0.620079879320342',
        'firsttime' => '60',
        'firsttime_outof' => '170',
        'firsttime_mean' => '0.352941176470588',
        'firsttime_95_low' => '0.316289099856428',
        'firsttime_95_high' => '0.389593253084748',
    ),

    'council' => array(
        'dispatched_success' => '3720',
        'responded' => '1229',
        'responded_outof' => '2497',
        'responded_mean' => '0.492190628754505',
        'responded_95_low' => '0.48218584388162',
        'responded_95_high' => '0.502195413627391',
        'firsttime' => '1253',
        'firsttime_outof' => '2365',
        'firsttime_mean' => '0.529809725158562',
        'firsttime_95_low' => '0.519546562511479',
        'firsttime_95_high' => '0.540072887805646',
    ),


    'total' => array(
        'total' => true,
        'dispatched_success' => '42515',
        'responded' => '17822',
        'responded_outof' => '29793',
        'firsttime' => '12363',
        'firsttime_outof' => '28525',
    ),
);
?>
