<?php
/* Automatically generated by fyr/bin/stats-yearly-zeitgeist */

$zeitgeist_by_summary_type_2005 = array(
    'europe' => array(
        'dispatched_success' => '7069',
        'responded' => '2088',
        'responded_outof' => '3971',
        'firsttime' => '1322',
        'firsttime_outof' => '3630',
    ),

    'devolved' => array(
        'dispatched_success' => '1750',
        'responded' => '455',
        'responded_outof' => '1095',
        'firsttime' => '372',
        'firsttime_outof' => '1016',
    ),

    'westminster' => array(
        'dispatched_success' => '29976',
        'responded' => '14050',
        'responded_outof' => '22229',
        'firsttime' => '9416',
        'firsttime_outof' => '21513',
    ),

    'council' => array(
        'dispatched_success' => '3720',
        'responded' => '1229',
        'responded_outof' => '2497',
        'firsttime' => '1253',
        'firsttime_outof' => '2365',
    ),


    'total' => array(
        'dispatched_success' => '42515',
        'responded' => '17822',
        'responded_outof' => '29792',
        'firsttime' => '12363',
        'firsttime_outof' => '28524',
    ),
);
?>
